from graphene import InputObjectType, String, Float, Decimal, Int, DateTime, List, Boolean

# CustomerPayment
# Supplier

class BasicForeignKeyInputObject(InputObjectType):
    UID = String()
    Code = String()
    URI = String()

class DisplayIDForeignKeyInputObject(InputObjectType):
    UID = String()
    Name = String()
    DisplayID = String()
    URI = String()

class NameForeignKeyInputObject(InputObjectType):
    UID = String()
    Code = String()
    Name = String()
    URI = String()

class CurrencyForeignKeyInputObject(InputObjectType):
    UID = String()
    Code = String()
    CurrencyName = String()
    URI = String()

class InvoicesInputObject(InputObjectType):
    RowID = Int()
    Number = String()
    UID = String()
    AmountApplied = Decimal()
    AmountAppliedForeign = Decimal()
    Type = String()
    URI = String()

class CustomerPaymentInputObject(InputObjectType):
    UID = String()
    DepositTo = String()
    Account = DisplayIDForeignKeyInputObject()
    Customer = DisplayIDForeignKeyInputObject()
    ReceiptNumber = String()
    Date = String()
    AmountReceived = Decimal()
    AmountReceivedForeign = Decimal()
    PaymentMethod = String()
    Memo = String()
    Invoices = InvoicesInputObject(),   
    TransactionID = String()
    ForeignCurrency = NameForeignKeyInputObject()
    CurrencyExchangeRate = Decimal()
    URI = String()
    RowVersion = String()

class AddressInputObject(InputObjectType):
    Location = Int()
    Street = String()
    City = String()
    State = String()
    PostCode = String()
    Country = String()
    Phone1 = String()
    Phone2 = String()
    Phone3 = String()
    Fax = String()
    Email = String()
    Website = String()
    ContactName = String()
    Salutation = String()

class CreditInputObject(InputObjectType):
    Limit = Decimal()
    Available = Decimal()
    PastDue = Decimal()

class ARIdentifierInputObject(InputObjectType):
    Label = String()
    Value = String()

class TermsInputObject(InputObjectType):
    PaymentIsDue = String()
    DiscountDate = Int()
    BalanceDueDate = Int()
    DiscountForEarlyPayment = Float()
    VolumeDiscount = Float()

class RefundInputObject(InputObjectType):
    PaymentMethod = String()
    CardNumber = String()
    NameOnCard = String()
    Notes = String()

class BuyingDetailsInputObject(InputObjectType):
    PurchaseLayout = String()
    PrintedForm = String()
    PurchaseOrderDelivery = String()
    ExpenseAccount = DisplayIDForeignKeyInputObject()
    PaymentMemo = String()
    PurchaseComment = String()
    SupplierBillingRate = Decimal()
    ShippingMethod = String()
    IsReportable = Boolean()
    CostPerHour = Decimal()
    Credit = CreditInputObject()
    ABN = String()
    ABNBranch = String()
    TaxIdNumber = String()
    TaxCode = BasicForeignKeyInputObject()
    FreightTaxCode = BasicForeignKeyInputObject()
    UseSupplierTaxCode = Boolean()
    Terms = TermsInputObject()

class PaymentDetailsInputObject(InputObjectType):
    BSBNumber = String()
    BankAccountNumber = String()
    BankAccountName = String()
    StatementText = String()
    StatementCode = String()
    StatementReference = String()
    Refund = RefundInputObject()

class SupplierInputObject(InputObjectType):
    UID = String()
    CompanyName = String()
    LastName = String()
    FirstName = String()
    IsIndividual = Boolean()
    DisplayID = String()
    IsActive = Boolean()
    Addresses = List(AddressInputObject)
    Notes = String()
    Identifiers = List(ARIdentifierInputObject)
    CustomList1 = ARIdentifierInputObject()
    CustomList2 = ARIdentifierInputObject()
    CustomList3 = ARIdentifierInputObject()
    CustomField1 = ARIdentifierInputObject()
    CustomField2 = ARIdentifierInputObject()
    CustomField3 = ARIdentifierInputObject()
    CurrentBalance = Decimal()
    BuyingDetails = BuyingDetailsInputObject()
    PaymentDetails = PaymentDetailsInputObject()
    ForeignCurrency = NameForeignKeyInputObject()
    LastModifiedDateTime = DateTime()
    PhotoURI = String()
    URI = String()
    RowVersion = String()

class InvoiceTermsInputObject(InputObjectType):
    PaymentIsDue = String()
    DiscountDate = Int()
    BalanceDueDate = Int()
    DiscountForEarlyPayment = Decimal()
    MonthlyChargeForLatePayment = Decimal()
    DiscountExpiryDate = DateTime()
    Discount = Decimal()
    DiscountForeign = Decimal()
    DueDate = DateTime()
    FinanceCharge = Decimal()
    FinanceChargeForeign = Decimal()

class InvoiceLinesInputObject(InputObjectType):
    RowID = Int()
    Type = String()
    Description = String()
    UnitsOfMeasure = String()
    UnitCount = Decimal()
    UnitPrice = Decimal()
    UnitPriceForeign = Decimal()
    DiscountPercent = Decimal()
    Total = Decimal()
    TotalForeign = Decimal()
    Account = DisplayIDForeignKeyInputObject()
    Job = NameForeignKeyInputObject()
    TaxCode = BasicForeignKeyInputObject()
    RowVersion = String()

class InvoiceInputObject(InputObjectType):
    UID = String()
    Number = String()
    Date = DateTime()
    CustomerPurchaseOrderNumber = String()
    Customer = DisplayIDForeignKeyInputObject()
    PromisedDate = DateTime()
    BalanceDueAmount = Decimal()
    BalanceDueAmountForeign = Decimal()
    Status = String()
    Lines = List(InvoiceLinesInputObject)
    ShipToAddress = String()
    Terms = InvoiceTermsInputObject()
    IsTaxInclusive = Boolean()
    Subtotal = Decimal()
    SubtotalForeign = Decimal()
    Freight = Decimal()
    FreightForeign = Decimal()
    FreightTaxCode = BasicForeignKeyInputObject()
    TotalTax = Decimal()
    TotalTaxForeign = Decimal()
    TotalAmount = Decimal()
    TotalAmountForeign = Decimal()
    Category = DisplayIDForeignKeyInputObject()
    Salesperson = DisplayIDForeignKeyInputObject()
    Comment = String()
    ShippingMethod = String()
    JournalMemo = String()
    ReferralSource = String()
    InvoiceDeliveryStatus = String()
    LastPaymentDate = DateTime()
    CanApplySurcharge = Boolean()
    Order = BasicForeignKeyInputObject()
    OnlinePaymentMethod = String()
    ForeignCurrency = CurrencyForeignKeyInputObject()
    CurrencyExchangeRate = Decimal()
    LastModified = DateTime()
    URI = String()
    RowVersion = String()