# Generated by Django 4.0 on 2023-03-16 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myob', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=63, verbose_name='Company Name')),
                ('logo_path', models.CharField(blank=True, max_length=255)),
                ('myob_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myob.myobuser')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('username', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=63)),
                ('last_name', models.CharField(blank=True, max_length=63)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('position', models.CharField(blank=True, max_length=31)),
                ('role', models.CharField(choices=[('GUS', 'General User'), ('SMU', 'Site Manager'), ('PMU', 'Project Manager'), ('EST', 'Estimator'), ('ADM', 'System Administrator'), ('DEV', 'Developer')], default='GUS', max_length=3)),
                ('profile_icon', models.ImageField(null=True, upload_to='')),
                ('signature', models.ImageField(null=True, upload_to='')),
                ('refresh_token', models.CharField(blank=True, max_length=1023)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last login')),
                ('is_active', models.BooleanField(default=True)),
                ('myob_access', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('default_pagination_amount', models.IntegerField(default=30)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='accounts.company')),
                ('myob_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myob.myobuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
