# Generated by Django 4.0 on 2022-07-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=63, verbose_name='First Name')),
                ('logo', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='signature',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('GUS', 'General User'), ('SMU', 'Site Manager'), ('PMU', 'Project Manager'), ('EST', 'Estimator'), ('ADM', 'Administrator')], default='GUS', max_length=3),
        ),
    ]
