# Generated by Django 4.2.13 on 2024-06-26 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myob', '0003_companyfile'),
        ('accounts', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='myob_account',
            new_name='default_myob_account',
        ),
        migrations.AddField(
            model_name='company',
            name='default_myob_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myob.companyfile'),
        ),
    ]
