# Generated by Django 4.0 on 2022-07-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_phone_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
