# Generated by Django 4.0 on 2022-08-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='default_pagination_amount',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='default_sidebar_toggle',
            field=models.BooleanField(default=False),
        ),
    ]
