# Generated by Django 4.0 on 2022-08-31 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myob', '0001_initial'),
        ('accounts', '0008_remove_customuser_default_sidebar_toggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='myob_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myob.myobuser'),
        ),
    ]
