# Generated by Django 4.0 on 2023-01-23 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myob', '0003_rename_expires_at_myobuser_access_expires_at'),
        ('accounts', '0009_customuser_myob_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='myob_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myob.myobuser'),
        ),
    ]
