# Generated by Django 4.0 on 2023-01-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_company_myob_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=63, verbose_name='Company Name'),
        ),
    ]
