# Generated by Django 4.0 on 2023-01-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_myob_access_alter_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
        migrations.AddField(
            model_name='company',
            name='logo_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
