# Generated by Django 4.0 on 2023-03-21 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('myob_uid', models.CharField(blank=True, max_length=36)),
                ('display_id', models.CharField(max_length=12)),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('level', models.IntegerField()),
                ('current_balance', models.DecimalField(decimal_places=2, default='0.00', max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('myob_uid', models.CharField(blank=True, max_length=36)),
                ('display_id', models.CharField(max_length=12)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('journal_type', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=13)),
                ('is_credit', models.BooleanField()),
                ('job_uid', models.CharField(blank=True, max_length=36)),
                ('job_number', models.CharField(blank=True, max_length=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.account')),
            ],
        ),
    ]
