# Generated by Django 4.0 on 2023-03-21 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_account_date_occurred_alter_sync_sync_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='date_occurred',
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_occurred',
            field=models.DateField(default=datetime.date(2023, 3, 22)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sync',
            name='sync_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 7, 1, 51, 958484)),
        ),
    ]
