# Generated by Django 4.0 on 2023-03-22 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_remove_account_date_occurred_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('myob_uid', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('myob_uid', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='job_number',
        ),
        migrations.AlterField(
            model_name='account',
            name='myob_uid',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='sync',
            name='sync_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 18, 13, 33, 466630)),
        ),
        migrations.AlterField(
            model_name='sync',
            name='sync_type',
            field=models.CharField(choices=[('ACC', 'Account'), ('TRA', 'Transaction'), ('CLI', 'Clients')], max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='journal_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='myob_uid',
            field=models.CharField(max_length=36),
        ),
    ]
