# Generated by Django 4.0 on 2023-03-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_client_job_remove_transaction_job_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sync',
            name='sync_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
