# Generated by Django 4.0 on 2023-03-16 01:51

import api.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('myob_uid', models.CharField(blank=True, max_length=36, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=80)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientRegion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=80, null=True)),
                ('bill_to_address', models.CharField(max_length=256)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('myob_uid', models.CharField(blank=True, max_length=38, null=True)),
                ('name', models.CharField(max_length=200)),
                ('abn', models.CharField(max_length=12)),
                ('bsb', models.CharField(max_length=8)),
                ('bank_account_name', models.CharField(max_length=52)),
                ('bank_account_number', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=20)),
                ('description', models.CharField(default='', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstimateHeader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(default='', max_length=50)),
                ('markup', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('gross', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('estimate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estimate')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('myob_uid', models.CharField(blank=True, max_length=36, null=True)),
                ('number', models.CharField(blank=True, max_length=13, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=13)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('date_paid', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('myob_uid', models.CharField(blank=True, max_length=36, null=True)),
                ('stage', models.CharField(choices=[('INS', 'Inspection Required'), ('QUO', 'Quote Required'), ('SUB', 'Quote Submitted'), ('APP', 'Quote Approved'), ('QAR', 'Quote Approval Required'), ('UND', 'Works Underway'), ('CLO', 'Close Out Required'), ('INV', 'Invoicing'), ('BSA', 'BSAFE Submission'), ('PAY', 'Awaiting Payment'), ('FIN', 'Finalised'), ('CAN', 'Cancelled'), ('PRO', 'Project')], default='INS', editable=False, max_length=3)),
                ('po', models.CharField(max_length=10)),
                ('sr', models.CharField(blank=True, max_length=10)),
                ('other_id', models.CharField(blank=True, max_length=10)),
                ('priority', models.CharField(blank=True, max_length=4)),
                ('building', models.CharField(blank=True, max_length=20)),
                ('detailed_location', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('special_instructions', models.TextField(blank=True, max_length=255)),
                ('scope', models.TextField(blank=True, max_length=500)),
                ('poc_name', models.CharField(blank=True, max_length=50)),
                ('poc_phone', models.CharField(blank=True, max_length=50)),
                ('poc_email', models.EmailField(blank=True, max_length=254)),
                ('alt_poc_name', models.CharField(blank=True, max_length=50)),
                ('alt_poc_phone', models.CharField(blank=True, max_length=50)),
                ('alt_poc_email', models.EmailField(blank=True, max_length=254)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('inspection_notes', models.TextField(blank=True, max_length=500)),
                ('commencement_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('total_hours', models.IntegerField(blank=True, default=0)),
                ('work_notes', models.TextField(blank=True, max_length=500)),
                ('close_out_date', models.DateField(blank=True, null=True)),
                ('close_out_reference', models.CharField(blank=True, max_length=10)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('overdue_date', models.DateField(blank=True, null=True)),
                ('opportunity_type', models.CharField(default='Commercial', max_length=20)),
                ('bsafe_link', models.CharField(blank=True, max_length=515)),
                ('work_type', models.CharField(default='Reactive Maintenance', max_length=20)),
                ('cancelled', models.BooleanField(default=False)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('client', models.ForeignKey(default=api.models.Client.get_default_id, on_delete=django.db.models.deletion.PROTECT, to='api.client')),
                ('inspection_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspector', to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('note', models.CharField(max_length=200)),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('myob_uid', models.CharField(blank=True, max_length=36, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.contractor')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.job')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressClaim',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('claim_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('note', models.CharField(max_length=200)),
                ('myob_uid', models.CharField(blank=True, max_length=36, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.contractor')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.job')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('client_ref', models.CharField(blank=True, max_length=4, null=True)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('NSW', 'New South Wales'), ('QLD', 'Queensland'), ('VIC', 'Victoria'), ('TAS', 'Tasmania'), ('WA', 'Western Australia'), ('SA', 'South Australia'), ('ACT', 'Australian Capital Territory'), ('NT', 'Nothern Territory')], default='NSW', max_length=3)),
                ('postcode', models.CharField(default='0000', max_length=4)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.client')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.clientregion')),
            ],
        ),
        migrations.CreateModel(
            name='JobInvoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.invoice')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.job')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.location'),
        ),
        migrations.AddField(
            model_name='job',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.clientcontact'),
        ),
        migrations.AddField(
            model_name='job',
            name='site_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_manager', to='accounts.customuser'),
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(default='', max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('item_type', models.CharField(blank=True, choices=[('', ''), ('quote', 'Quote'), ('quantity', 'Quantity'), ('item', 'Item'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('m', 'Meter'), ('m2', 'Sqauare Meter'), ('m3', 'Cubed Meter'), ('kg', 'Kilogram'), ('tonne', 'Tonne'), ('bag', 'Bag')], default='', max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('extension', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('markup', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('gross', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('header_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estimateheader')),
            ],
        ),
        migrations.AddField(
            model_name='estimate',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.job'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='quote_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.customuser'),
        ),
        migrations.CreateModel(
            name='ContractorContact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('contact', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('NSW', 'New South Wales'), ('QLD', 'Queensland'), ('VIC', 'Victoria'), ('TAS', 'Tasmania'), ('WA', 'Western Australia'), ('SA', 'South Australia'), ('ACT', 'Australian Capital Territory'), ('NT', 'Nothern Territory')], default='NSW', max_length=3)),
                ('postcode', models.CharField(max_length=4)),
                ('phone1', models.CharField(max_length=12)),
                ('phone2', models.CharField(max_length=12)),
                ('phone3', models.CharField(max_length=12)),
                ('fax', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=80)),
                ('website', models.EmailField(max_length=80)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.contractor')),
            ],
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.clientregion'),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('myob_uid', models.CharField(blank=True, max_length=36, null=True)),
                ('process_date', models.DateField(default=datetime.date.today)),
                ('invoice_date', models.DateField()),
                ('invoice_number', models.CharField(blank=True, max_length=13, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=13)),
                ('img_path', models.CharField(blank=True, max_length=32)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.job')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.contractor')),
            ],
        ),
    ]
