# Generated by Django 4.0 on 2022-08-01 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_profile_icon'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='approved',
        ),
        migrations.AlterField(
            model_name='job',
            name='inspection_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspector', to='accounts.customuser'),
        ),
        migrations.AlterField(
            model_name='job',
            name='site_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_manager', to='accounts.customuser'),
        ),
        migrations.AlterField(
            model_name='location',
            name='bgis_region',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
