# Generated by Django 4.0 on 2023-03-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='abn',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='bsb',
            field=models.CharField(max_length=10),
        ),
    ]
