# Generated by Django 4.0 on 2023-03-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_contractor_abn_alter_contractor_bsb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='other_id',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='job',
            name='po',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='job',
            name='sr',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
