# Generated by Django 4.0 on 2022-08-02 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_estimate_approved_alter_job_inspection_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRegion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='bgis_region',
        ),
        migrations.AddField(
            model_name='location',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.client'),
        ),
    ]
