# Generated by Django 4.0 on 2022-08-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_clientregion_remove_location_bgis_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientregion',
            name='email',
            field=models.EmailField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='clientregion',
            name='shortName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
