# Generated by Django 4.0 on 2023-03-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_job_other_id_alter_job_po_alter_job_sr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='alt_poc_name',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='job',
            name='alt_poc_phone',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='job',
            name='close_out_reference',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='detailed_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='opportunity_type',
            field=models.CharField(default='Commercial', max_length=24),
        ),
        migrations.AlterField(
            model_name='job',
            name='poc_name',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='job',
            name='poc_phone',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
