# Generated by Django 4.0 on 2023-03-16 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_job_building_alter_job_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
