# Generated by Django 4.0 on 2023-03-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_estimate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimateheader',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
