# Generated by Django 4.0 on 2023-04-04 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_estimateheader_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontact',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.clientregion'),
        ),
        migrations.AlterField(
            model_name='job',
            name='stage',
            field=models.CharField(choices=[('INS', 'Inspection/Quote Required'), ('SUB', 'Quote Submitted'), ('APP', 'Quote Approved'), ('QAR', 'Quote Approval Required'), ('UND', 'Works Underway'), ('CLO', 'Close Out Required'), ('INV', 'Invoicing'), ('BSA', 'BSAFE Submission'), ('PAY', 'Awaiting Payment'), ('FIN', 'Finalised'), ('CAN', 'Cancelled'), ('PRO', 'Project')], default='INS', editable=False, max_length=3),
        ),
    ]
