# Generated by Django 4.0 on 2022-08-02 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_shortname_clientregion_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontact',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.clientregion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.clientregion'),
            preserve_default=False,
        ),
    ]
