# Generated by Django 4.0 on 2022-08-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_clientcontact_region_location_region'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='base_id',
            new_name='client_ref',
        ),
        migrations.AlterField(
            model_name='job',
            name='po',
            field=models.CharField(max_length=10, verbose_name='Purchase Order Number'),
        ),
    ]
