# Generated by Django 4.0 on 2022-08-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_employee_rename_base_id_location_client_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='bsafe_link',
            field=models.CharField(blank=True, max_length=515, verbose_name='BSAFE Link'),
        ),
        migrations.AlterField(
            model_name='job',
            name='stage',
            field=models.CharField(choices=[('INS', 'Inspection Required'), ('QUO', 'Quote Required'), ('SUB', 'Quote Submitted'), ('APP', 'Quote Approved'), ('UND', 'Works Underway'), ('CLO', 'Close Out Required'), ('INV', 'Invoicing'), ('PAY', 'Awaiting Payment'), ('COM', 'Completed'), ('CAN', 'Cancelled'), ('PRO', 'Project')], default='INS', editable=False, max_length=3, verbose_name='Stage'),
        ),
    ]
