# Generated by Django 4.0 on 2023-04-24 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='issue_date',
            field=models.DateField(default=datetime.date(2023, 4, 24)),
            preserve_default=False,
        ),
    ]
