# Generated by Django 4.0 on 2022-08-09 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_job_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientregion',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.client'),
            preserve_default=False,
        ),
    ]
