# Generated by Django 4.0 on 2023-06-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_insurance_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='location',
            name='client_ref',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='locality',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
