# Generated by Django 4.0 on 2022-08-11 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_customuser_default_sidebar_toggle'),
        ('api', '0012_clientregion_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='quote_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientregion',
            name='short_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
