# Generated by Django 4.0 on 2023-06-28 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_location_address_alter_location_client_ref_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientRegion',
            new_name='Region',
        ),
    ]
