# Generated by Django 4.0 on 2022-08-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_estimate_quote_by_alter_clientregion_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='myob_uid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='myob_uid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='myob_uid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='progressclaim',
            name='myob_uid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='myob_uid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
