# Generated by Django 4.0 on 2023-07-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_clientregion_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='display_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
