# Generated by Django 4.0 on 2023-07-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_client_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontact',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contractorcontact',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
