# Generated by Django 4.0 on 2023-08-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_clientcontact_active_contractorcontact_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='display_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
