# Generated by Django 4.0 on 2022-08-31 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_invoice_amount_invoice_date_invoice_myob_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
