# Generated by Django 4.0 on 2023-08-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_client_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
