# Generated by Django 4.0 on 2022-08-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_job_invoice_delete_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('myob_uid', models.CharField(blank=True, max_length=36, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=13, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=13)),
            ],
        ),
    ]
