# Generated by Django 4.0 on 2022-08-31 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.invoice'),
        ),
    ]
