# Generated by Django 4.0 on 2023-08-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_client_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='inspection_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
