# Generated by Django 4.0 on 2022-08-31 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_job_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_number',
            new_name='number',
        ),
    ]
