# Generated by Django 4.0 on 2023-08-21 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_job_close_out_date_alter_job_commencement_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='inspection_time',
        ),
    ]
