# Generated by Django 4.0 on 2022-08-31 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_invoice_number_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='invoice',
        ),
        migrations.CreateModel(
            name='JobInvoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.invoice')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.job')),
            ],
        ),
    ]
