# Generated by Django 4.0 on 2022-08-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_job_invoice_jobinvoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='date',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='job',
            name='invoice_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='paid_date',
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_issued',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_paid',
            field=models.DateField(blank=True, null=True),
        ),
    ]
