# Generated by Django 4.0 on 2023-08-29 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_job_inspection_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='total_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
