# Generated by Django 4.0 on 2022-09-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_date_invoice_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='stage',
            field=models.CharField(choices=[('INS', 'Inspection Required'), ('QUO', 'Quote Required'), ('SUB', 'Quote Submitted'), ('APP', 'Quote Approved'), ('UND', 'Works Underway'), ('CLO', 'Close Out Required'), ('INV', 'Invoicing'), ('BSA', 'BSAFE Submission'), ('PAY', 'Awaiting Payment'), ('FIN', 'Finalised'), ('CAN', 'Cancelled'), ('PRO', 'Project')], default='INS', editable=False, max_length=3, verbose_name='Stage'),
        ),
    ]
