# Generated by Django 4.0 on 2022-12-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_job_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcontact',
            name='title',
        ),
        migrations.AlterField(
            model_name='job',
            name='stage',
            field=models.CharField(choices=[('INS', 'Inspection Required'), ('QUO', 'Quote Required'), ('SUB', 'Quote Submitted'), ('APP', 'Quote Approved'), ('QAR', 'Quote Approval Required'), ('UND', 'Works Underway'), ('CLO', 'Close Out Required'), ('INV', 'Invoicing'), ('BSA', 'BSAFE Submission'), ('PAY', 'Awaiting Payment'), ('FIN', 'Finalised'), ('CAN', 'Cancelled'), ('PRO', 'Project')], default='INS', editable=False, max_length=3, verbose_name='Stage'),
        ),
    ]
