# Generated by Django 4.0 on 2023-09-23 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_invoice_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobInvoice',
        ),
    ]
