# Generated by Django 4.0 on 2023-09-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_delete_jobinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='img_path',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
