# Generated by Django 4.0 on 2022-12-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_clientcontact_title_alter_job_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientregion',
            name='bill_to_address',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
