# Generated by Django 4.0 on 2022-12-26 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_clientregion_bill_to_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientcontact',
            old_name='company',
            new_name='client',
        ),
    ]
