# Generated by Django 4.0 on 2023-09-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_bill_img_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='thumbnail_path',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
