# Generated by Django 4.0 on 2022-12-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_company_clientcontact_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progressclaim',
            old_name='company',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='company',
            new_name='client',
        ),
        migrations.AddField(
            model_name='contractor',
            name='email',
            field=models.EmailField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractor',
            name='phone',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
