# Generated by Django 4.0 on 2023-09-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_bill_thumbnail_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='img_path',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(default='Subcontractor', max_length=16),
        ),
    ]
