# Generated by Django 4.0 on 2022-12-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_rename_company_progressclaim_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('NSW', 'New South Wales'), ('QLD', 'Queensland'), ('VIC', 'Victoria'), ('TAS', 'Tasmania'), ('WA', 'Western Australia'), ('SA', 'South Australia'), ('ACT', 'Australian Capital Territory'), ('NT', 'Nothern Territory')], default='NSW', max_length=3)),
                ('postcode', models.CharField(max_length=4)),
                ('phone1', models.CharField(max_length=12)),
                ('phone2', models.CharField(max_length=12)),
                ('phone3', models.CharField(max_length=12)),
                ('fax', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=80)),
                ('website', models.EmailField(max_length=80)),
            ],
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='state',
        ),
    ]
