# Generated by Django 4.0 on 2022-12-28 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_contractorcontact_remove_contractor_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorcontact',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='api.contractor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contractorcontact',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
