# Generated by Django 4.0 on 2023-10-15 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_bill_file_path_alter_bill_bill_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemittanceAdvice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('myob_uid', models.CharField(max_length=36)),
                ('date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.client')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='remittance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.remittanceadvice'),
        ),
    ]
