# Generated by Django 4.0 on 2022-12-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_contractorcontact_company_alter_contractorcontact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='opportunity_type',
            field=models.CharField(default='Commercial', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_type',
            field=models.CharField(default='Reactive Maintenance', max_length=20),
        ),
    ]
