# Generated by Django 4.0 on 2023-01-07 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_job_opportunity_type_alter_job_work_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('myob_uid', models.CharField(blank=True, max_length=36, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('invoice_number', models.CharField(blank=True, max_length=13, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=13)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.contractor')),
            ],
        ),
        migrations.CreateModel(
            name='JobBill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.bill')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.job')),
            ],
        ),
    ]
