# Generated by Django 4.0 on 2023-01-07 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_bill_job_delete_jobbill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='date_created',
            new_name='date',
        ),
    ]
