# Generated by Django 4.0 on 2024-01-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_job_other_id_alter_job_po_alter_job_sr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractorcontact',
            name='contact',
        ),
        migrations.AddField(
            model_name='contractorcontact',
            name='location',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
