# Generated by Django 4.0 on 2023-01-07 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_rename_date_created_bill_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='date',
            new_name='process_date',
        ),
    ]
