# Generated by Django 4.0 on 2023-01-07 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_rename_date_bill_process_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='process_date',
            new_name='invoice_date',
        ),
    ]
