# Generated by Django 4.0 on 2024-01-31 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_role'),
        ('api', '0034_contractorcontact_contact_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('myob_uid', models.CharField(blank=True, max_length=36, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('locale', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=13)),
                ('expense_date', models.DateField()),
                ('thumbnail_path', models.CharField(blank=True, max_length=512)),
                ('file_path', models.CharField(blank=True, max_length=512)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='accounts.customuser')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.job')),
            ],
        ),
    ]
