# Generated by Django 4.0 on 2024-01-31 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='process_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
