# Generated by Django 4.0 on 2023-02-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_bill_invoice_date_alter_bill_process_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='img_name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
