# Generated by Django 4.0 on 2023-02-17 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_bill_img_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='img_name',
            new_name='img_path',
        ),
    ]
