# Generated by Django 4.0 on 2023-03-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_rename_img_name_bill_img_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimateitem',
            name='item_type',
            field=models.CharField(blank=True, choices=[('', ''), ('item', 'Item'), ('quote', 'Quote'), ('quantity', 'Quantity'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('m', 'Meter'), ('m2', 'Sqauare Meter'), ('m3', 'Cubed Meter'), ('kg', 'Kilogram'), ('tonne', 'Tonne'), ('bag', 'Bag')], default='', max_length=10),
        ),
    ]
