# Generated by Django 4.0 on 2024-05-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_contractorcontact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='short_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
