# Generated by Django 4.2.13 on 2024-06-26 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myob', '0003_companyfile'),
        ('api', '0041_alter_region_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='myob_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myob.companyfile'),
        ),
    ]
