# Generated by Django 4.0 on 2022-08-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyobUser',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(blank=True, max_length=125)),
                ('access_token', models.CharField(blank=True, max_length=512)),
                ('refresh_token', models.CharField(blank=True, max_length=512)),
            ],
        ),
    ]
