# Generated by Django 4.0 on 2023-03-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myobuser',
            name='access_token',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='myobuser',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
