# Generated by Django 4.0 on 2022-09-05 00:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myob', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myobuser',
            name='expires_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
