# Generated by Django 4.0 on 2022-09-05 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myob', '0002_myobuser_expires_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myobuser',
            old_name='expires_at',
            new_name='access_expires_at',
        ),
    ]
