# Generated by Django 4.2.13 on 2024-06-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myob', '0002_alter_myobuser_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=36, unique=True)),
                ('file_id', models.CharField(max_length=36, unique=True)),
            ],
        ),
    ]
