# Generated by Django 4.0 on 2023-07-13 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('myob_uid', models.CharField(max_length=38, unique=True)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('work_type', models.CharField(max_length=32)),
                ('job', models.CharField(blank=True, max_length=32)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('employee', models.CharField(max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timesheets.workday')),
            ],
        ),
    ]
