# Generated by Django 4.0 on 2023-07-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0003_remove_timesheet_work_workday_timesheet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='sent_to_myob',
            field=models.BooleanField(default=False),
        ),
    ]
