# Generated by Django 4.0 on 2023-07-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0004_timesheet_sent_to_myob'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
