# Generated by Django 4.0 on 2023-07-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0005_employee_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pay_basis',
            field=models.CharField(choices=[('SA', 'Salary'), ('HR', 'Hourly')], default='SA', max_length=2),
        ),
    ]
