# Generated by Django 4.0 on 2023-07-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0006_employee_pay_basis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pay_basis',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Hourly', 'Hourly')], default='Salary', max_length=6),
        ),
    ]
