# Generated by Django 4.0 on 2023-07-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0007_alter_employee_pay_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='overtime',
            field=models.BooleanField(default=False),
        ),
    ]
