# Generated by Django 4.0 on 2023-07-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0009_rename_overtime_workday_allow_overtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('myob_uid', models.CharField(max_length=38, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('type', models.CharField(choices=[('wage', 'Wage'), ('entitlement', 'Entitlement'), ('deduction', 'Deduction'), ('expense', 'Expense'), ('superannuation', 'Superannuation'), ('tax', 'Tax'), ('tax_table', 'Tax Table')], default='wage', max_length=255)),
            ],
        ),
    ]
