# Generated by Django 4.0 on 2023-07-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0010_payrollcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollcategory',
            name='type',
            field=models.CharField(choices=[('wage', 'Wage'), ('entitlement', 'Entitlement'), ('deduction', 'Deduction'), ('expense', 'Expense'), ('superannuation', 'Superannuation'), ('tax', 'Tax'), ('taxtable', 'Tax Table')], default='wage', max_length=255),
        ),
    ]
