# Generated by Django 4.0 on 2023-07-19 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0011_alter_payrollcategory_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payrollcategory',
            old_name='type',
            new_name='pr_type',
        ),
    ]
