# Generated by Django 4.0 on 2023-07-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0013_remove_payrollcategory_pr_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
