# Generated by Django 4.0 on 2023-08-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0015_timesheet_myob_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyobJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('myob_uid', models.CharField(max_length=38, unique=True)),
                ('number', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SyncSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('jobs', models.DateField(auto_now=True)),
            ],
        ),
    ]
