# Generated by Django 4.0 on 2023-08-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0016_myobjob_syncsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='job',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
