# Generated by Django 4.0 on 2023-08-07 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0017_alter_workday_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='timesheets.myobjob'),
        ),
    ]
